services:
  app:
    image: confession-wall:latest
    container_name: confession-wall
    restart: unless-stopped
    #生产环境下，后端、数据库、redis缓存将不再暴露至容器网络外部，有调试需要请自行取消注释
    #ports:
      #- "8080:8080"   # 宿主机 8080 映射到容器 8080
    environment:
      #JWT_SECRET: "${JWT_SECRET}"        # 可在 .env 文件或宿主机传入
      #注意，环境变量或配置文件二选一，配置文件比环境变量有着更高的优先级
      SERVER_PORT: 8080 #服务监听端口
      SERVER_LISTEN_ADDR: "0.0.0.0"  #服务监听地址，生产环境建议只监听本地接口不修改本项
      APP_DATABASE_HOST: db #数据库地址
      APP_DATABASE_PORT: 3306        #数据库端口
      APP_DATABASE_USERNAME: root    #数据库用户
      APP_DATABASE_PASSWORD: rootpassword   #数据库密码
      APP_DATABASE_NAME: confession  #数据库名称
      APP_REDIS_ADDR: "redis:6379"      #redis地址
      APP_REDIS_PASSWORD: password123       #redis密码
      APP_REDIS_DB: 0                #redis数据库
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads  # 持久化上传的图片
      - ./data:/app/data  # 配置文件，环境变量或配置文件二选一，配置文件比环境变量有着更高的优先级

  nginx:
    image: nginx:latest
    container_name: confession-frontend
    restart: unless-stopped
    ports:
      - "11732:11732"      # 或 "8080:8080" 按需映射，前端端口自行修改nginx.conf文件
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载你的nginx配置
      - ./dist:/app/dist                                   # 挂载编译得到的前端静态资源
      - ./uploads:/app/uploads                             # 挂载上传目录
    depends_on:
      - app
  db:
    image: mysql:latest
    container_name: confession-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: confession
    #ports:
      #- "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # 持久化数据库
  redis:
    image: redis:latest
    container_name: confession-redis
    restart: unless-stopped
    #ports:
      #- "6379:6379"
    volumes:
      - ./redis/data:/data 
      - ./redis/redis.conf:/etc/redis/redis.conf  # 持久化 Redis 配置