server:
  port: 8080
  host: "localhost"

database:
  host: "localhost"
  port: 5432
  name: "mysql"
  username: "user"
  password: "example-password"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

log:
  level: "debug"
  file: "app.log"